services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-mistral
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
    external: true
